### ISSUE TITLE
Inconsistent behavior in `cl_fix_from_real`

### ISSUE THREAD

**Issue by hcommin** [enclustra/en_cl_fix#9]
The [Python implementation](https://github.com/enclustra/en_cl_fix/blob/master/python/src/en_cl_fix_pkg.py) of `cl_fix_from_real` rounds ties asymmetrically towards +Inf:
```python
x = np.floor(a*(2.0**rFmt.FracBits)+0.5)/2.0**rFmt.FracBits
```

The [MATLAB implementation](https://github.com/enclustra/en_cl_fix/blob/master/matlab/src/cl_fix_from_real.m) rounds ties symmetrically away from zero:
```matlab
% round symmetrically to infinity (same as VHDL)
result = round (a.*2^result_fmt.FracBits).*2^-result_fmt.FracBits;
```

The comment in the MATLAB code suggests this is the same behavior as the [VHDL implementation](https://github.com/enclustra/en_cl_fix/blob/master/vhdl/src/en_cl_fix_pkg.vhd). I think this is true for the _latest_ implementation, which uses the `round` function:
```vhdl
ASat_v := round(ASat_v * 2.0**(result_fmt.FracBits));
```

However, it's probably worth noting that this was not necessarily true for the implementation prior to 6f06f349393f2637e157a512a5cd90a5e6378253:
```vhdl
temp_v := integer (ASat_v * 2.0**result_fmt.FracBits);	-- as, 
```

According to the VHDL LRM (IEEE Std 1076-2019, section 9.3.6):
> The conversion of a floating-point value to an integer type rounds to the nearest integer;
> if the value is halfway between two integers, rounding may be up or down.

So I think the behavior is implementation-specific (the VHDL standard allows ties to be rounded up or down).

I plan to fix this inconsistency in the near future.

**Comment by hcommin** [comment]
More inconsistent behavior in this function:

In the [VHDL implementation](https://github.com/enclustra/en_cl_fix/blob/master/vhdl/src/en_cl_fix_pkg.vhd), the `saturate` input is ignored. Saturation is always applied without warning.

In the [MATLAB implementation](https://github.com/enclustra/en_cl_fix/blob/master/matlab/src/cl_fix_from_real.m), the `saturate` input appears to be used correctly.

In the [Python implementation](https://github.com/enclustra/en_cl_fix/blob/master/python/src/en_cl_fix_pkg.py), `Warn_s` and `SatWarn_s` have been incorrectly elevated to errors.

I plan to fix this inconsistency in the near future.

**Comment by hcommin** [comment]
More inconsistent behavior in this function:

When saturation is **disabled**:
- The VHDL implementation applies saturation anyway.
- The MATLAB implementation wraps the value.
- The Python implementation leaves the value out of range.

I plan to fix this inconsistency in the near future.

**Comment by hcommin** [comment]
More inconsistent behavior in this function:

When saturation is **disabled**:
- The VHDL implementation saturates anyway.
- The MATLAB implementation wraps.
- The Python implementation leaves the value out of range.

Note: this is also inconsistent with the behavior of `cl_fix_resize` (all implementations appear to wrap).

**Comment by hcommin** [comment]
## Tasks
1. Rounding behavior
    - MATLAB is now consistent with Python because MATLAB calls Python.
    - [ ] Convert VHDL to half-up rounding (+ verify).
2. Saturation behavior
    - MATLAB is now consistent with Python because MATLAB calls Python.
    - [ ] Implement the specified saturation mode (+ verify).
3. Wrapping behavior
    - MATLAB is now consistent with Python because MATLAB calls Python.
    - [ ] Make the Python implementation wrap, so it is consistent with the VHDL (+ verify).
